# Generated by Django 4.2.2 on 2023-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ID бота TG'),
        ),
    ]
